### ISSUE TITLE
i18Date helper requires type and and pattern

### ISSUE THREAD

**Issue by stephentcannon** [arsnebula/cosmo#2]
This throws an error

````
{{i18nDate '2015-01-01'}}
````

````
Exception in template helper: [object Object]: E_INVALID_PAR_VALUE: Invalid `{"name":"pattern","value":{"[object Object]":"short"}}` value (undefined).
````

This does not.
````
{{i18nDate '2015-01-01' 'date' 'short'}}
````

Default of type and pattern doesn't seem to be happening.

**Comment by chrismbeckett** [comment]
Thanks for the tip, and I appreciate you trying out this package. In all honestly, while I think the jQuery Globalize is the most complete i18n solution out there, wiring it together and trying to make it work with Meteor turned out to be more work than I would have liked, and I think this package probablies requires a whole lot more testing and trial before I would trust it in a production application. I really don't intend to support this package moving forward since I am not really using Meteor much anymore, so please use it as a reference package for your own needs, or feel free to fork it.
